// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sat Apr 23 13:11:18 2022

AM AM_inst
(
	.carrier(carrier_sig) ,	// input [15:0] carrier_sig
	.modulated(modulated_sig) ,	// input [15:0] modulated_sig
	.ma(ma_sig) ,	// input [3:0] ma_sig
	.AM_sig(AM_sig_sig) 	// output [15:0] AM_sig_sig
);

